-- Database: db_condominio

-- DROP DATABASE IF EXISTS db_condominio;

CREATE DATABASE db_condominio
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

	CREATE TABLE EDIFICIO (
    	ID SERIAL PRIMARY KEY,
   	 	ENDERECO VARCHAR(100)
	);

	SELECT * FROM 	EDIFICIO
	
	CREATE TABLE APTO (
    	ID SERIAL PRIMARY KEY,
    	NUMERO INT,
    	AREA DECIMAL(10,2),
   	 	ID_EDI INT,
   	 	FOREIGN KEY (ID_EDI) REFERENCES EDIFICIO(ID)
	);

	SELECT * FROM 	APTO
	
	INSERT INTO EDIFICIO (ENDERECO) VALUES 
	('Rua A, 123'),
	('Rua B, 456'),
	('Rua C, 789');

	SELECT * FROM 	EDIFICIO
	
	INSERT INTO APTO (NUMERO, AREA, ID_EDI) VALUES
	(101, 50.5, 1),
	(102, 60.0, 1),
	(201, 70.2, 2);

	SELECT * FROM 	APTO

	DELETE FROM APTO;

	SELECT * FROM 	APTO

	DELETE FROM APTO
	WHERE ID_EDI = 1;
	
	SELECT * FROM 	APTO
	
	DELETE FROM EDIFICIO
	WHERE ID = 1;

	SELECT * FROM 	EDIFICIO
	
	