-- Database: livraria

-- DROP DATABASE IF EXISTS livraria;

CREATE DATABASE livraria
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

	
	CREATE TABLE CLIENTE (
	    ID_CLI SERIAL PRIMARY KEY,
	    NOME VARCHAR(100),
	    TELEFONE VARCHAR(20),
	    ENDERECO VARCHAR(150)
	);

	INSERT INTO CLIENTE (NOME, TELEFONE, ENDERECO)
	VALUES 
	('Ana Lima', '11977777777', 'Rua C, 789'),
	('Bruno Costa', '11966666666', 'Rua D, 321');

	SELECT * FROM CLIENTE;
	
	CREATE TABLE LIVRO (
	    ID_LIV SERIAL PRIMARY KEY,
	    TITULO VARCHAR(150),
	    AUTOR VARCHAR(100),
	    EDITORA VARCHAR(100),
	    PRECO DECIMAL(10,2),
	    ESTOQUE INT
	);

	INSERT INTO LIVRO (TITULO, AUTOR, EDITORA, PRECO, ESTOQUE)
	VALUES 
	('Java Básico', 'José Santos', 'TechBooks', 80.00, 10),
	('Banco de Dados', 'Maria Oliveira', 'DataEditora', 120.00, 5),
	('Algoritmos', 'Carlos Pereira', 'DevEditora', 90.00, 8);

	SELECT * FROM LIVRO;
	
	CREATE TABLE PEDIDO (
	    ID_PED SERIAL PRIMARY KEY,
	    DATA DATE,
	    VALOR_TOT DECIMAL(10,2),
	    STATUS VARCHAR(50),
	    ID_CLI INT,
	    FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI)
	);

	INSERT INTO PEDIDO (DATA, VALOR_TOT, STATUS, ID_CLI)
	VALUES 
	('2026-04-01', 160.00, 'Aguardando', 1),
	('2026-04-02', 120.00, 'Pago', 2);

	SELECT * FROM PEDIDO;
	
	CREATE TABLE ITEM_PEDIDO (
	    ID_ITE SERIAL PRIMARY KEY,
	    ID_PED INT,
	    ID_LIV INT,
	    QUANTIDADE INT,
	    VALOR_UNI DECIMAL(10,2),
	    FOREIGN KEY (ID_PED) REFERENCES PEDIDO(ID_PED),
	    FOREIGN KEY (ID_LIV) REFERENCES LIVRO(ID_LIV)
	);

	INSERT INTO ITEM_PEDIDO (ID_PED, ID_LIV, QUANTIDADE, VALOR_UNI)
	VALUES 
	(1, 1, 2, 80.00),
	(2, 2, 1, 120.00);

	SELECT * FROM ITEM_PEDIDO;
	
	CREATE TABLE PAGAMENTO (
	    ID_PAG SERIAL PRIMARY KEY,
	    ID_PED INT UNIQUE,
	    VALOR DECIMAL(10,2),
	    DATA_PAG DATE,
	    STATUS VARCHAR(50),
	    FOREIGN KEY (ID_PED) REFERENCES PEDIDO(ID_PED)
	);

	INSERT INTO PAGAMENTO (ID_PED, VALOR, DATA_PAG, STATUS)
	VALUES 
	(2, 120.00, '2026-04-02', 'Pago');

	SELECT * FROM PAGAMENTO;

	