-- Database: oficina_mecanica

-- DROP DATABASE IF EXISTS oficina_mecanica;

CREATE DATABASE oficina_mecanica
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

	CREATE TABLE CLIENTE (
	    ID_CLI SERIAL PRIMARY KEY,
	    NOME VARCHAR(100),
	    TELEFONE VARCHAR(20),
	    ENDERECO VARCHAR(150)
	);

	INSERT INTO CLIENTE (NOME, TELEFONE, ENDERECO)
	VALUES 
	('João Silva', '11999999999', 'Rua A, 123'),
	('Maria Souza', '11988888888', 'Rua B, 456');

	SELECT * FROM CLIENTE
	
	CREATE TABLE VEICULO (
	    ID_VEI SERIAL PRIMARY KEY,
	    PLACA VARCHAR(10),
	    MODELO VARCHAR(50),
	    MARCA VARCHAR(50),
	    ID_CLI INT,
	    FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI)
	);
	
	INSERT INTO VEICULO (PLACA, MODELO, MARCA, ID_CLI)
	VALUES 
	('ABC1234', 'Civic', 'Honda', 1),
	('XYZ5678', 'Gol', 'Volkswagen', 2);
	
	SELECT * FROM VEICULO
	
	CREATE TABLE MECANICO (
	    ID_MEC SERIAL PRIMARY KEY,
	    NOME VARCHAR(100),
	    ESPECIALIDADE VARCHAR(100)
	);
	
	INSERT INTO MECANICO (NOME, ESPECIALIDADE)
	VALUES 
	('Carlos', 'Motor'),
	('Pedro', 'Freios');
	
	SELECT * FROM MECANICO

	CREATE TABLE ORCAMENTO (
	    ID_ORC SERIAL PRIMARY KEY,
	    DATA DATE,
	    STATUS VARCHAR(50),
	    VALOR_TOT DECIMAL(10,2),
	    ID_VEI INT,
	    ID_MEC INT,
	    FOREIGN KEY (ID_VEI) REFERENCES VEICULO(ID_VEI),
	    FOREIGN KEY (ID_MEC) REFERENCES MECANICO(ID_MEC)
	);
	
	INSERT INTO ORCAMENTO (DATA, STATUS, VALOR_TOT, ID_VEI, ID_MEC)
	VALUES 
	('2026-04-01', 'Em análise', 500.00, 1, 1),
	('2026-04-02', 'Aprovado', 300.00, 2, 2);

	SELECT * FROM ORCAMENTO

	CREATE TABLE SERVICO (
	    ID_SER SERIAL PRIMARY KEY,
	    DESCRICAO VARCHAR(150),
	    VALOR_UNI DECIMAL(10,2)
	);
	
	INSERT INTO SERVICO (DESCRICAO, VALOR_UNI)
	VALUES 
	('Troca de óleo', 100.00),
	('Alinhamento', 150.00);

	SELECT * FROM SERVICO

	CREATE TABLE ITEM_ORCAMENTO (
	    ID_ITE SERIAL PRIMARY KEY,
	    ID_ORC INT,
	    ID_SER INT,
	    QUANTIDADE INT,
	    VALOR_TOT DECIMAL(10,2),
	    FOREIGN KEY (ID_ORC) REFERENCES ORCAMENTO(ID_ORC),
	    FOREIGN KEY (ID_SER) REFERENCES SERVICO(ID_SER)
	);
	
	INSERT INTO ITEM_ORCAMENTO (ID_ORC, ID_SER, QUANTIDADE, VALOR_TOT)
	VALUES 
	(1, 1, 2, 200.00),
	(2, 2, 1, 150.00);
	
	SELECT * FROM ITEM_ORCAMENTO

	CREATE TABLE PAGAMENTO (
	    ID_PAG SERIAL PRIMARY KEY,
	    ID_ORC INT UNIQUE,
	    VALOR DECIMAL(10,2),
	    DATA_PAG DATE,
	    STATUS VARCHAR(50),
	    FOREIGN KEY (ID_ORC) REFERENCES ORCAMENTO(ID_ORC)
	);
	
	INSERT INTO PAGAMENTO (ID_ORC, VALOR, DATA_PAG, STATUS)
	VALUES 
	(2, 300.00, '2026-04-03', 'Pago');

	SELECT * FROM PAGAMENTO