-- Database: aula_Aula03b

-- DROP DATABASE IF EXISTS "aula_Aula03b";

CREATE DATABASE "aula_Aula03b"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


	CREATE TABLE ALUNO (
    RGM INT,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(200),
    TELEFONE VARCHAR(20)
	);

	CREATE TABLE DISCIPLINA (
    CODIGO INT,
    NOME VARCHAR(100),
    EMENTA TEXT
	);

	CREATE TABLE ALUNO_DISCIPLINA (
    COD_ALU INT,
    COD_DIS INT,
    NOTA1 NUMERIC(5,2),
    NOIA2 NUMERIC(5,2),
    MEDIA NUMERIC(5,2),
    FALTAS INT
	);

	ALTER TABLE ALUNO ADD CONSTRAINT PK_ALUNO PRIMARY KEY (RGM);
	
	ALTER TABLE DISCIPLINA ADD CONSTRAINT PK_DISCIPLINA PRIMARY KEY (CODIGO);

	ALTER TABLE ALUNO_DISCIPLINA ADD CONSTRAINT FK_ALUNO FOREIGN KEY (COD_ALU) REFERENCES ALUNO(RGM);

	ALTER TABLE ALUNO_DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA FOREIGN KEY (COD_DIS) REFERENCES DISCIPLINA(CODIGO);
	
	ALTER TABLE ALUNO ADD COLUMN RG VARCHAR(20);
	
	ALTER TABLE ALUNO ADD COLUMN CPF VARCHAR(14);

	ALTER TABLE ALUNO ALTER COLUMN CPF SET NOT NULL;
	
	ALTER TABLE ALUNO ADD CONSTRAINT UNIQUE_CPF UNIQUE (CPF);

	ALTER TABLE ALUNO_DISCIPLINA DROP COLUMN FALTAS;

	ALTER TABLE ALUNO_DISCIPLINA RENAME TO NOTAS;

	ALTER TABLE NOTAS ALTER COLUMN MEDIA SET NOT NULL;

	ALTER TABLE ALUNO RENAME TO ALUNOS;

	ALTER TABLE ALUNOS DROP COLUMN RGM;

	ALTER TABLE NOTAS DROP CONSTRAINT FK_ALUNO;
	
	ALTER TABLE ALUNOS DROP CONSTRAINT PK_ALUNO;
	
	ALTER TABLE ALUNOS DROP COLUMN RGM;

	DROP TABLE DISCIPLINA;
	
	DROP TABLE DISCIPLINA CASCADE;

	DROP TABLE NOTAS CASCADE;
	
	DROP TABLE ALUNOS CASCADE;
	