-- Database: db_aula03

-- DROP DATABASE IF EXISTS db_aula03;

CREATE DATABASE db_aula03
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

	CREATE TABLE TESTE (
		CODIGO NUMERIC(5) NOT NULL,
		SALARIO NUMERIC(7, 2),
		DIA_HOJE DATE,
		TEXTO VARCHAR(10),
		APROVADO BOOLEAN
	)

	INSERT INTO TESTE (CODIGO, SALARIO, DIA_HOJE, TEXTO, APROVADO) VALUES
	(123, 455.56, '2012-03-19', 'Hello', TRUE),
	(99999, 99999.56, '2012-03-19', 'Ola', FALSE);

	ALTER TABLE TESTE RENAME TO AULABD;

	ALTER TABLE AULABD RENAME COLUMN APROVADO TO SITUACAO;

	ALTER TABLE AULABD ADD RGM NUMERIC(5);

	ALTER TABLE AULABD ADD NOVO_CAMPO VARCHAR(100);

	UPDATE AULABD SET NOVO_CAMPO = 'OK' WHERE NOVO_CAMPO IS NULL;

	ALTER TABLE AULABD ALTER COLUMN NOVO_CAMPO SET NOT NULL;

	ALTER TABLE AULABD DROP COLUMN SALARIO;

	UPDATE AULABD SET RGM = 1 WHERE CODIGO = 123;

	UPDATE AULABD SET RGM = 2 WHERE  CODIGO = 99999;

	SELECT * FROM AULABD WHERE RGM IS NULL;
	
	ALTER TABLE AULABD ALTER COLUMN RGM SET NOT NULL;

	ALTER TABLE AULABD ADD CONSTRAINT PK_RGM PRIMARY KEY (RGM);

	SELECT * FROM AULABD;
	
	DROP TABLE AULABD;

	

	